/****************************************************************************
 * boards/risc-v/sg2002/licheerv_nano/scripts/ld.script
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/
MEMORY
{
    ram (rwx) : ORIGIN = 0x8FE00000, LENGTH = 2048K  /* 0x8FE00000 ~ 0x81000000 */
}

OUTPUT_ARCH("riscv")
EXTERN(_vectors)
ENTRY(_stext)

SECTIONS
{
  .text :
    {
      _stext = ABSOLUTE(.);
      KEEP (*(.vectors))
      *(.text .text.*)
      *(.gnu.warning)
      *(.stub)
      *(.glue_7)
      *(.glue_7t)
      *(.jcr)
      *(.gnu.linkonce.t.*)
      *(.init)
      *(.fini)
      _etext = . ;
    } > ram

  .rodata : ALIGN(4)
    {
      _srodata = . ;
      *(.rodata .rodata.*)
      *(.rodata1)
      *(.gnu.linkonce.r*)
      _erodata = . ;
    } > ram

  .tdata : ALIGN(4)
    {
      _stdata = ABSOLUTE(.);
      *(.tdata .tdata.* .gnu.linkonce.td.*);
      _etdata = ABSOLUTE(.);
    } > ram

  .tbss : ALIGN(4)
    {
      _stbss = ABSOLUTE(.);
      *(.tbss .tbss.* .gnu.linkonce.tb.* .tcommon);
      _etbss = ABSOLUTE(.);
    } > ram

  _eronly = ABSOLUTE(.);

  .data : ALIGN(4)
    {
      _sdata = ABSOLUTE(.);
      *(.data .data.*)
      *(.data1)
      *(.gnu.linkonce.d*)
      . = ALIGN(4);
      _edata = ABSOLUTE(.);
    } > ram

  .bss (NOLOAD): ALIGN(4)
    {
      _sbss = ABSOLUTE(.);
      *(.bss .bss.*)
      *(.sbss .sbss.*)
      *(.gnu.linkonce.b*)
      *(COMMON)
      . = ALIGN(32);
      _ebss = ABSOLUTE(.);
    } > ram

  .stack_top (NOLOAD):
    {
      . = ALIGN(32);
      _stack_top = ABSOLUTE(.);
    } > ram

  .stab 0 : { *(.stab) }
  .stabstr 0 : { *(.stabstr) }
  .stab.excl 0 : { *(.stab.excl) }
  .stab.exclstr 0 : { *(.stab.exclstr) }
  .stab.index 0 : { *(.stab.index) }
  .stab.indexstr 0 : { *(.stab.indexstr) }
  .comment 0 : { *(.comment) }
  .debug_abbrev 0 : { *(.debug_abbrev) }
  .debug_info 0 : { *(.debug_info) }
  .debug_line 0 : { *(.debug_line) }
  .debug_pubnames 0 : { *(.debug_pubnames) }
  .debug_aranges 0 : { *(.debug_aranges) }
}
